### ISSUE TITLE
pybuilder and test coverage

### ISSUE THREAD

**Issue by szaghi** [Fortran-FOSS-Programmers/ford#13]
Hi Chris,

The new release is great! The PyPi publishing is very useful.

As future improvment I suggest you to try pybuilder http://pybuilder.github.io

It is very helpful to automate developing/testing/mantainance. In particular, I am very happy with the testing facilities... 

Another future improvment could be the refactoring of project tree in order to be more pythonish: put the sources into a main src directory and deploy on PyPi the built releases created, for example, by means of pybuilder. I follow this approach for MaTiSSe (https://github.com/szaghi/MaTiSSe) and this simplifies my life.

**Comment by cmacmackin** [comment]
I will do this at some point, but it is not on the immediate horizon. It looks like it would take too much time that I really should be devoting to school. I might get to it during my winter break in late February. Otherwise it will have to wait until after the semester is over.

**Comment by szaghi** [comment]
Sure, don't worry. This is just a suggestion for the future.

School must be your priority. 

See you soon.

**Comment by ZedThree** [comment]
Testing, formatting, and publishing now all automated via Github Actions
