### ISSUE TITLE
exclude removes all instance of file

### ISSUE THREAD

**Issue by pavanakumar** [Fortran-FOSS-Programmers/ford#253]
Hi

At present ```exclude:``` in project md file removes all occurrences of the file in the project.

We actually have different versions of the same file (name) for GPU and CPU implementations.

Ideally, we like to generate the documentation based on CMake configure options (CPU or GPU). But adding the file to ford removes all occurrences. Is it possible to explicitly specify the file name with the full relative path?

--
Kumar

**Comment by ZedThree** [comment]
Fixed in #558
