### ISSUE TITLE
FORD crashes for undefined type-bound procedure

### ISSUE THREAD

**Issue by PaulXiCao** [Fortran-FOSS-Programmers/ford#255]
FORD crashes with unrecognizable statements for undefined type-bound procedures. Check out the example below

```fortran
module foo_m

  implicit none

  type foo_t
  contains
    procedure :: bar
  end type foo_t

end module foo_m
```

**Comment by ZedThree** [comment]
This is invalid Fortran: 

```
app/example.f90:7:13:

    7 |     procedure :: bar
      |             1
Error: 'bar' must be a module procedure or an external procedure with an explicit interface at (1)
Compiler returned: 1
```

There's now a `--force` option to make Ford ignore errors that might be able to handle this, but otherwise I think this is unsupported, sorry
