### ISSUE TITLE
"Read more" doesn't lead anywhere when the target is not included in documentation

### ISSUE THREAD

**Issue by jhrmnn** [Fortran-FOSS-Programmers/ford#267]
When a subroutine is private and accessible publicly only as a public bound procedure of a type, it doesn't have its own page. The list of bound procedures shows only summaries of documentation. If the documentation of such a subroutine has more than a one paragraph, the additional paragraph won't be accessible, because the "Read more" link doesn't lead anywhere.

**Comment by albgar** [comment]
@jhrmnn: Would you mind preparing a pull request for this small patch? I have been putting it off and now I am not sure about how best to go about it.

**Comment by jhrmnn** [comment]
I have since forgot everything about the code, so I'd have to go through everything again. Also, do you mean that I should prepare a PR with your patch above?

**Comment by albgar** [comment]
Ah! Don’t worry, then. I will try to make the PR myself.

 Alberto

**Comment by ZedThree** [comment]
Looks like this was fixed in #282
