### ISSUE TITLE
One-line if and call graphs

### ISSUE THREAD

**Issue by johandweber** [Fortran-FOSS-Programmers/ford#275]
Hi,
I am currently learning to use ford. 

I have a question concerning the interpretation of subroutines in conditional clauses.

I have found that while a function call  of the type

if (condition)
  call do_something
end if

is recognized as a call of a subroutine, while

if (condition)&
   call something

is not.

I am not sure whether this is intended behavior, a 
result of the choice of options  in the configuration file
or maybe an issue of ford.

Here is a reduced testcase

```
program ford_if_test
  implicit none
  write(*,*) "Hello, "
  if (.true.) &
       call sub1
  if (.true.) then
     call sub2
  end if
end program ford_if_test

subroutine sub1
  implicit none
  write(*,*) "World."
end subroutine sub1

subroutine sub2
  implicit none
  write(*,*) "How are you?"
end subroutine sub2
```

The corresponding configuration file is

```
author: J. A. Weber 
display: public 
         protected 
         private
fpp_extensions: fpp
graph: true
output_dir: ./doc
proc_internals: true
project: ford_if_test
search: true
source: true
src_dir: ./zz2source
summary: A test program for conditional calls
version: 0.0.0


```

The menu item "Procedures" then leads to the output below
![ford_if_test](https://user-images.githubusercontent.com/38630799/53810116-8c97b280-3f56-11e9-850b-0b4b387cfc01.png)

**Comment by ecasglez** [comment]
It works properly for me, see attached screenshot. I use Ubuntu 18.04 and python 3.6.9. Might it depend on the OS and the Python version?

![imagen](https://user-images.githubusercontent.com/29178639/105077823-5b162a80-5a8d-11eb-9af5-0eb50ec9113a.png)

**Comment by ZedThree** [comment]
Looks like this has been fixed at some point.
