### ISSUE TITLE
bug to link calls with explicit arrays in input

### ISSUE THREAD

**Issue by OscarBaseggio** [Fortran-FOSS-Programmers/ford#278]
Ford doesn't link the calls with explicit arrays in input, as for example, I change 
call do_stuff(20)
with
call do_stuff(array(1)).
and in documentation there isn't the link between ford_test_program and do_stuff

[FORD-test.zip](https://github.com/Fortran-FOSS-Programmers/ford/files/3042424/FORD-test.zip)

**Comment by kc9jud** [comment]
Is this still a problem after #257?

**Comment by OscarBaseggio** [comment]
yes, my problem persists

**Comment by OscarBaseggio** [comment]
My problem is fixed
