### ISSUE TITLE
Code blocks don't seem to work within subroutines

### ISSUE THREAD

**Issue by laurarnichols** [Fortran-FOSS-Programmers/ford#287]
Using "```" before and after code works in most pages to create a code block, but it doesn't work within subroutines

**Comment by cmacmackin** [comment]
Could you please provide a reproducer for this?

**Comment by laurarnichols** [comment]
Yes, sorry! Okay, well I guess the issue is that the code blocks aren't working as I would expect in documentation inside any level (program, module, subroutine, etc.).

If I use something like (I know the comments don't match and this isn't a useful example, but it should reproduce the issue):
```fortran
program myProgram
  !! Here is a summary of my program
  !! 
  !! General form is
  !! ```
  !! subroutine readInput(fileName)
  !!   ! Get input
  !!   ! Test input validity
  !!   ! Output success or failure
  !! ```
  implicit none
  integer :: x
  write(*,*) x
end program myProgram
```
then I get
![image](https://user-images.githubusercontent.com/32521892/60670931-7d0e7480-9e37-11e9-808a-bd0daa1376a6.png)

I also tried adding line breaks before and after to be safe and adding `fortran` as the language, but then I get
![image](https://user-images.githubusercontent.com/32521892/60671272-5ef54400-9e38-11e9-9479-2cdf9c4c2d35.png)

**Comment by dbroemmel** [comment]
I think I'm running into a similar issue. I'm not used to markdown and currently have what you might call ASCII drawings inside comments that I'd like to show up in the documentation as well as inside the code. I was also looking for a way to include those 'as is' in fixed-width font. I'm guessing this would look like a code block.
I have a FORD processed comment like
```
!  topology:  npe=12
!
!             -------------------------
!             |  2  |  5  |  8  | 11  |
!             -------------------------
!  x, xnpe=3  |  1  |  4  |  7  | 10  |      0.le.mpe.le.npe-1
!             -------------------------
!             |  0  |  3  |  6  |  9  |
!             -------------------------
!                     y, ynpe=4
```
that turns into
![image](https://user-images.githubusercontent.com/25457511/61126611-35c65a80-a4ad-11e9-9cf9-66e5591c2af0.png)
which is not really what I'm after. I could get linebreaks by adding two spaces at the end and also remove the box by skipping the blank line, but then I'm still stuck without fixed-width fonts.  
I too tried back-ticks which then produced text in red like above.

Did I miss an option to enable a different processing?

**Comment by laurarnichols** [comment]
I randomly discovered that you can actually get code blocks within subroutines by having two blank lines before. As an example, 
```fortran
  !!   <h3>Usage</h3>
  !!
  !!
  !!        DOUBLE PRECISION V(3), Y(5*5)
  !!        V(1) = ...
  !!        V(2) = ...
  !!        V(3) = ...
  !!        CALL YLM(V,4,Y)
  !!
```
produces
![image](https://user-images.githubusercontent.com/32521892/61729985-0da4ea00-ad3e-11e9-84f3-4a5611d18a6d.png)

The syntax highlighting isn't perfect, but it's better than nothing. This is definitely unexpected behavior though because normal markdown does not do that. It just provides a workaround until the issue is fixed/addressed.

**Comment by ecasglez** [comment]
The problem is the same as with issue #286. You need to remove the space between ```!!``` and ``` `` ```.

```fortran
program myProgram
  !! Here is a summary of my program
  !!  
  !! General form is
  !!```fortran
  !! subroutine readInput(fileName)
  !!   ! Get input
  !!   ! Test input validity
  !!   ! Output success or failure
  !!```
  implicit none
  integer :: x
  write(*,*) x
end program myProgram
```
