### ISSUE TITLE
graphviz error

### ISSUE THREAD

**Issue by econwang** [Fortran-FOSS-Programmers/ford#290]
I install the `graphviz` package, and in python, `from graphviz import Digraph` works well, but `ford` still shows 

> Warning: Will not be able to generate graphs. Graphviz not installed.

**Comment by AntonioRochaAZ** [comment]
@econwang How did you fix this? I have the same problem...

**Comment by helenespringsintef** [comment]
I was having the same problem and fixed it in the following way. install graphviz from [their website](https://graphviz.org/) directly. When going through the steps in the installation wizard, select 'add graphviz to path'. Then FORD will be able to find graphviz. You can also solve this problem by ensuring your pip installation of graphviz is added to the system path, but the way I did it is the simplest.
