### ISSUE TITLE
Exception: Alternate documentation lines can not be inline error

### ISSUE THREAD

**Issue by wadudmiah** [Fortran-FOSS-Programmers/ford#295]
Hi,

What does the following error mean?

Exception: Alternate documentation lines can not be inline

Thanks in advance for any help.
Wadud.

**Comment by cmacmackin** [comment]
Alternate documentation is when you use a marker on the first line and all
subsequent lines that are comments are treated as part of that block of
documentation. Inline documentation refers to documentation at the end of a
line of code. For reasons I can't quite remember you can not use alternate
documentation in an inline manner. Either start the documentation on a new
line or switch to regular documentation.

**Comment by wadudmiah** [comment]
Hi Chris, 

thanks for the quick response. I am now getting this error:

ValueError: substring not found

Any help will be appreciated!
Wadud.

**Comment by cmacmackin** [comment]
That is definitely a bug. Without more context I can't offer much help.

**Comment by wadudmiah** [comment]
I think I found the bug in FORD. The code below causes it to fail:

`    Module mrks_mod
      Character*19 mrks(:)
      Allocatable mkrlabels
    End Module`

This gives the error:

`i = name.index('(')
ValueError: substring not found`

If this is changed to the following, FORD works:

`    Module mrks_mod
      Character*19, allocatable :: mrks(:)
    End Module`

**Comment by wadudmiah** [comment]
I am also getting this error:

>   File "/usr/lib64/python2.7/site-packages/ford/reader.py", line 263, in __next__
>    if line[-1] == '&':
> IndexError: string index out of range

The line that is causing this error is shown below:

>                 # Check if line will be continued
>                if line[-1] == '&':

Looks like something to do with line break continuation or something similar.

**Comment by ZedThree** [comment]
@wadudmiah The issue in your first comment is fixed, we've improved the error message that's printed when this happens. I can no longer reproduce the issues in your other comments, so I'm closing this now
