### ISSUE TITLE
Warning: Could not extract source code for proc

### ISSUE THREAD

**Issue by eamousing** [Fortran-FOSS-Programmers/ford#299]
Hi,

I just cannot figure out how to extract source code from procedures. Here is a simple example:

```fortran
module functions
    !! This module contains some functions and subroutines
    implicit none
    contains
    function testfunction(x, y) result(res)
        !! This is a test function
        !!
        !! $$res = x + y$$
        real, intent(in) :: x !! First input real
        real, intent(in) :: y !! Second input real
        real :: res !! Sum of x and y
        res = x + y
    end function testfunction
end module functions
```
I get the error "Warning: Could not extract source code for proc testfunction in file functions.f90" but I cannot see what is wrong. 

Using FORD version 6 and this is the project file:

```
project: Test project
author: Test
source: true
graph: true
warn: true
```

Any help will be appreciated!

Best,
Erik

**Comment by ZedThree** [comment]
Hi Erik, this seems to have been fixed at some point in the last three years! Feel free to reopen this if it's still a problem for you, but I couldn't reproduce this with the latest version
