### ISSUE TITLE
Various parser issues

### ISSUE THREAD

**Issue by pclausen** [Fortran-FOSS-Programmers/ford#304]
Hi 

I really like this doc tool, but unfortunately I cant run it on our source base because of a couple of minor parser issues.

Below is am example file which causing the issues. You can reproduce by copy pasting this in a new file, eg. _ford_issues.f90_, and then

```bash
$ python ford/reader.py ford_issues_bad.f90
``` 

```Fortran
! compile wtih
!> ifort /fpp /openmp ford_issues.f90

module ford_issues
#if defined(__GFORTRAN__)

#else
  use ifport
#endif  
  use omp_lib  
  implicit none

contains

  ! this is function with args that have comments
  integer function func_with_args(a, & 
  &                               b, & ! this is not OK
  &                               c ) 
    integer :: a, b, c
  
    func_with_args = a+b
  end function 

  ! this is OK
  integer function func_with_bracket()
    double precision :: auxf, L_min
    
    ! this is OK  
    auxf = ( 1.0d0 - L_min)
    
    ! this fails  
!  File "e:\nosave\code\gitrepos\ford\ford\reader.py", line 218, in __next__
! raise Exception("Alternate documentation lines can not be inline: {}".format(line))
! Exception: Alternate documentation lines can not be inline:     auxf = ( 1.0d0 - L_min)!* (1.0d0 - L_min)    
    auxf = ( 1.0d0 - L_min)!* (1.0d0 - L_min)
  
    func_with_bracket = 5
  end function 

    ! this fails
!  File "e:\nosave\code\gitrepos\ford\ford\sourceform.py", line 1371, in _initialize
!  for arg in self.SPLIT_RE.split(line.group(3)[1:-1]):
! TypeError: 'NoneType' object is not subscriptable
  integer function func_without_bracket
    integer :: omp_p
    
    ! this also fails
! File "e:\nosave\code\gitrepos\ford\ford\reader.py", line 261, in __next__
! raise Exception("Can not start a new line in Fortran with \"&\": {}".format(line))
! Exception: Can not start a new line in Fortran with "&": & PRIVATE( omp_p )
    !$OMP PARALLEL DEFAULT(SHARED) &
   & PRIVATE( omp_p )

    !$OMP CRITICAL
      write(*,*)  'thread ', omp_get_thread_num(), '/', omp_get_num_threads(), ' started'
    !$OMP END CRITICAL

    !$OMP END PARALLEL
      
    func_without_bracket = 10
  end function 
  
end module ford_issues

program main
  use ford_issues
  implicit none
  
  integer :: i(3)
  i(1) = func_with_args(0,1,0)
  i(2) = func_with_bracket()
  i(3) = func_without_bracket()
  write(*,*) 'ford_issues', i
end program
```

**Comment by haraldkl** [comment]
The first one

> auxf = ( 1.0d0 - L_min)!* (1.0d0 - L_min)

is because of the commented out multiplication, the !* is parsed as a alternate documentation mark, you need to either remove the commented code or put break the `!*` sequence up (by a space for example).

The last one
> !$OMP PARALLEL DEFAULT(SHARED) &
>   & PRIVATE( omp_p )

is bad OpenMP, I believe. The second line should also start with the openmp mark like `!$OMP&`. 

What remains are functions without argument lists. My best guess here is to just add empty argument lists.

**Comment by pclausen** [comment]
@haraldkl  Thanks, I will try it out

**Comment by pclausen** [comment]
I have added a PR #305 adding a trivial regression test which I have added for doing my own investigation of the code. I am not sure if you want unit tests and if this is the right way of doing it, so please comment.

**Comment by pclausen** [comment]
@haraldkl 

> > !$OMP PARALLEL DEFAULT(SHARED) &
> > & PRIVATE( omp_p )
> 
> is bad OpenMP, I believe. The second line should also start with the openmp mark like `!$OMP&`.

Thanks. Fixing this, the parsing works for one of my directories. :-)

**Comment by ZedThree** [comment]
` integer function func_without_bracket` is non-standard Fortran, looks like about half the compilers I tested accept this or issue a warning/error with a standard specified, and the other half error.

I think only `!*` is Ford-specific, and can presumably be solved by specifying the docmark.
