### ISSUE TITLE
Fortran include files not properly processed

### ISSUE THREAD

**Issue by ecasglez** [Fortran-FOSS-Programmers/ford#308]
I am programming some generic functions and the code is added in some external include files to avoid repetition. When I launched Ford to generate the documentation, the funcions called from those included files do not show up properly in the html output.

I simplified the code to produce the following example with the basic functions: [fordtest.zip](https://github.com/Fortran-FOSS-Programmers/ford/files/4656192/fordtest.zip)

Analyzing the html output, you can see the relation between the functions of the module named "works" as in the following figure:

![imagen](https://user-images.githubusercontent.com/29178639/82436592-5af50380-9a96-11ea-8a3e-7ca8ab1fd51e.png)

On the other hand, the functions of the module name "notworks" do not show that relation, as in the following figure:

![imagen](https://user-images.githubusercontent.com/29178639/82436706-8aa40b80-9a96-11ea-85e6-aa8bd7d6f3a0.png)

I am using Ford version 6.0.0.

**Comment by ecasglez** [comment]
The problem was that Ford only detected include statements if they were written using lowercase characters. I submitted pull request #313 with the changes to fix this.

**Comment by ZedThree** [comment]
Fixed in #313
