### ISSUE TITLE
FORD links in code blocks get expanded

### ISSUE THREAD

**Issue by ZedThree** [Fortran-FOSS-Programmers/ford#309]
FORD links like `[[module:subroutine]]` in a triple-backtick code block get parsed as links rather than raw text.

MVCE:

foo.f90:
```Fortran
subroutine foo
end subroutine foo
```

config.md:

    ---
    src_dir: .
    output_dir: ./docs
    ---
    
    ```text
    This should not be a link [[foo]]
    ```

Produces the following line in `docs/index.html`:

```
<div class="codehilite"><pre><span></span><code>This should not be a link <a href="./proc/foo.html">foo</a>
```

**Comment by awvwgk** [comment]
I'm currently running into this issue when including TOML, especially using the array of tables, in documents processed by FORD.

I would be interested in helping with a fix on this issue in FORD.

**Comment by ZedThree** [comment]
The [wikilinks extension](https://python-markdown.github.io/extensions/wikilinks/) has a `build_url` option that takes a callable which _almost_ works. Unfortunately, we need to know the `project` object to be able to build the URL and we don't have that until after we set the extensions in the markdown `md` object.

One solution, which feels a little hacky, would be to use a class like:

```python
class LinkBuilder:
   def set_project(self, project):
       self.project = project

   def __call__(self, label, base, end):
       # implementation basically follows current sub_links
       # but returns the URL and not the link tag
```

We could then use an instance of this as the `build_url` argument:

```python
    proj_data["link_builder"] = LinkBuilder()
    md_ext = [
        ..., 
        WikiLinkExtension(build_url=proj_data["link_builder"]),
    ]
    md = markdown.Markdown(extensions=md_ext, output_format="html5", extension_configs={})
```

and then in `Project` we do `settings["link_builder"].set_project(self)`
