### ISSUE TITLE
Question: disable sourcecode pages

### ISSUE THREAD

**Issue by pirpyn** [Fortran-FOSS-Programmers/ford#314]
Hi, thanks for this tools, which for as far as I used, works perfectly.

I wonder if I missed in the wiki an option to disable the copy of the source code in the documentation.
I don't wan't the following to be included in the doc. Is it possible ?

This list of source files
![source_list](https://user-images.githubusercontent.com/13225186/89100376-d0664400-d3f6-11ea-9f33-9778e15890b1.png)

And the whole file source code.
![source](https://user-images.githubusercontent.com/13225186/89100375-cfcdad80-d3f6-11ea-9afc-3573afdf49ae.png)

**Comment by ecasglez** [comment]
You can add ```incl_src=false``` in the input file of ford.

**Comment by pirpyn** [comment]
Thanks, 
This is almost perfect as it removes all source code, but the list of source file names is still there.
Also I had to replace `=` with `:`.

**Comment by ecasglez** [comment]
I submitted pull request #316 to fix the list of source files showing when incl_src is false.

**Comment by ZedThree** [comment]
Fixed in #316
