### ISSUE TITLE
"Unknown Procedure Type" in call tree

### ISSUE THREAD

**Issue by Koushikphy** [Fortran-FOSS-Programmers/ford#319]
I'm getting so many "Unknown Procedure Type" in the call tree graph, although I call properly compile and run the codes. How to fix this.  
Also, I'm getting a few variables/arrays in the call tree,  which shouldn't be there, as they are not being called.

**Comment by ZedThree** [comment]
Hi @Koushikphy, would you be able to point me at some code where this happens?

**Comment by Koushikphy** [comment]
Use this sample code 

```
module mymod
    implicit none
    contains
    subroutine sub()
        print *, 'sub called'
        end
end module mymod


module thismod
    use mymod
end module thismod


program name
    use thismod
    implicit none
    call sub
end program name
```


The main program calls a subroutine that lies two inherited module away, so ford term the `sub` call in the main program as "unknowns procedure type"
