### ISSUE TITLE
Release 6.0.0 does not contain `ford/js/MathJax-config`

### ISSUE THREAD

**Issue by bassenj** [Fortran-FOSS-Programmers/ford#325]
When installing FORD 6.0.0 using pip3 ([FORD-6.0.0.tar.gz](https://files.pythonhosted.org/packages/cd/c0/30f1bdcf011f57a3810d252ed06329d0559260bda922dbc63f1932eebaa1/FORD-6.0.0.tar.gz)) `MathJax-config` directory is missing.
Therefore, `shutil.copy` fails when `mathjax_config` is given in the project file on Ubuntu 20.04.2 LTS.

**Comment by ZedThree** [comment]
This works for me now with 6.1.2, provided I used the tarball from PyPI and not Github. Please reopen this if you're still having trouble
