### ISSUE TITLE
Footnotes in Pages

### ISSUE THREAD

**Issue by jphaupt** [Fortran-FOSS-Programmers/ford#327]
If I use a footnote in one page, it appears in all subsequent (i.e. later-in-the-alphabet) pages, even if that footnote never appears in the subsequent page. I have not found a workaround. 

FWIW I am trying to use the footnotes for citations, in a BibTeX-style. E.g. having {!literature.md!} at the end of relevant files. This has another issue that all footnotes are included, not just the ones referenced in the doc.

**Comment by ZedThree** [comment]
@jphaupt Would you be able to create minimal reproducer so I can investigate and fix this?

**Comment by jphaupt** [comment]
Sorry for the delay, but it looks like you got it solved already. Thanks! :D
