### ISSUE TITLE
order of subroutine calls in call tree graphs

### ISSUE THREAD

**Issue by Koushikphy** [Fortran-FOSS-Programmers/ford#328]
The call tree shows the subroutine call order randomly. One of my program calls five subroutine but call tree shows them as 4th,5th,3rd,1st,2nd from top to bottom. They are not in alphabetical order too. I have mentioned in the project file as `srt=src`, but it doesn't shows that way.

**Comment by cmacmackin** [comment]
This is due to the behaviour of upstream dependency dot. Unfortunately, I
don't think there is anything I can do about this.

**Comment by ZedThree** [comment]
This was mostly fixed in #484
