### ISSUE TITLE
Automatic publishing of releases

### ISSUE THREAD

**Issue by ZedThree** [Fortran-FOSS-Programmers/ford#332]
We can get Github Actions to automatically upload packages to PyPI when we create releases: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

This works pretty well for the other repos I know that use it. 

@cmacmackin Please could you create a PyPI API token for FORD and add it as a repo secret? It sounds like you can limit the token to just the FORD project.

**Comment by cmacmackin** [comment]
I've added the token as `PYPI_DEPLOYMENT_TOKEN`. If you like I can also make you a collaborator on the PyPI project.

**Comment by ZedThree** [comment]
Great, thank you! Yes please, my username is `yossarian`, email is my York address

**Comment by cmacmackin** [comment]
I've sent you an invite. Would have done it sooner but seems the email slipped through the cracks.

**Comment by ZedThree** [comment]
Thanks! This is sorted now. Creating a new release on Github will now automatically build sdist + wheel and upload them to pypi.
