### ISSUE TITLE
Prep for 6.1.0 release

### ISSUE THREAD

**Issue by ZedThree** [Fortran-FOSS-Programmers/ford#341]
- [x] CHANGELOG and change summary
- [x] Update setup.py to use setup.cfg and pyproject.toml
- [x] Set up black and linting
- [x] Set up publishing GHA
- [ ] More end-to-end tests
- [ ] Set up sphinx/read-the-docs

**Comment by ecasglez** [comment]
Hi. Thank you for your big effort.

I think the wiki should also be updated with the latest changes such as:

* MIT license is now allowed in the project file options (wiki: Project File Options).
* project_gitlab is a new option in the project file options (wiki: Project File Options).
* Ordered_subpage can be used now in the pages (wiki: Writing Pages, issue: #307)
* Copy_subdir option can be used now in the pages (wiki: Writing Pages. Pull request: #302)

There might be other sections that should be updated too that I haven't been following.

**Comment by ZedThree** [comment]
Oh very good point, I'd also like to get some better documentation up on FORD itself

**Comment by ZedThree** [comment]
v6.1 is out, we should continue to add tests and non-wiki based documentation
