### ISSUE TITLE
somehow FORD takes number in Format  as subroutine to draw the graph

### ISSUE THREAD

**Issue by zxdi** [Fortran-FOSS-Programmers/ford#350]
I wrote a test to show that:

    Program test2
    !-----------------------------------------------------------------------
    !!     Fortran 2008
    !!-----------------------------------------------------------------------
    !!     Author      : Maosong Cheng                      DATE : 2018.04.13
    !!-----------------------------------------------------------------------
    !!     Modified by : zxdi                               DATE : 2021.07.15
    !-----------------------------------------------------------------------
    !
        Implicit None
        Write (*, 300)

    300 Format (/1X, 44('-'), ' Begin of test2 Calculation ', 33('-')//)

    End Program test2

And this is the .md file:

    src_dir: ./src
    output_dir: ./doc
    project: test2
    summary: test2
    author: Ms Cheng; Zxdi
    author_description: sinap
    email: aaa@bb.com
    date: %Y-%m-%d %H:%M %z
    fpp_extensions: fpp
    predocmark: >
    media_dir: ./media
    docmark_alt: #
    predocmark_alt: <
    display: public
            protected
            private  
    proc_internals: true
    source: true
    graph: true
    search: true  
    favicon: T_logo.png

FORD give me this, the '44'&'33' confuse me. Where did I do wrong?

![image](https://user-images.githubusercontent.com/24704786/128598631-dfae964a-0cbe-41a6-89c5-39ae21f0a73a.png)

**Comment by ZedThree** [comment]
Hi @zxdi, thanks for the bug report! It looks like Ford is interpreting the `44('-')` as a function call. I don't think function calls are allowed in a `format` statement, so perhaps we're not catching `format`s correctly.

**Comment by cmacmackin** [comment]
This is an example of why a proper parser would be helpful for FORD.
Function calls are just detected with a regex, without too much regard for
context. I'm not certain off the top of my head, but this might have
similar issues in strings (although I probably thought about that corner
case more than format statements).
