### ISSUE TITLE
Case sensitivity for MODULE SUBROUTINE

### ISSUE THREAD

**Issue by francescotorsello** [Fortran-FOSS-Programmers/ford#353]
[ford-possible-bug.zip](https://github.com/Fortran-FOSS-Programmers/ford/files/7134147/ford-possible-bug.zip)

Hi,

I might have found a small possible bug in FORD 6.1.1, and I have attached a minimal example that reproduces it.

If one uses uppercase or lowercase letters in the INTERFACE of a MODULE SUBROUTINE for the word "MODULE", FORD gives different results. Namely, I think that when using lowercase letters, everything goes as expected, but when using uppercase letters FORD does not recognize the MODULE SUBROUTINE as such. This does not happen with MODULE FUNCTION, where both lowercase and uppercase letters seem to work, at least in my experience.

Also, if I run FORD with the option "sort: alpha", and immediately afterwards I run it with the option "sort: type" or "sort: type-alpha", error messages are printed during its execution. However, if I delete the documentation before the second run, no error messages appear.

Hope this helps improving FORD, which I think is a great tool!

Best wishes

**Comment by ZedThree** [comment]
Thanks for the bug report and reproducer @francescotorsello !

Yes, it looks like using when using uppercase in the interface, Ford doesn't produce a link to the implementation.

Are the errors like `shutil.SameFileError`? If so, this is a known issue, we should ignore the output directory. A workaround for now is to make sure the output directory isn't a subdirectory of your source directory.

**Comment by francescotorsello** [comment]
You're welcome!

The error appears after the message
`Correlating information from different parts of your project...`
and reads 
`TypeError: can only concatenate str (not "FortranType") to str`

My output directory is not a subdirectory of the source directory. Hope this helps!

**Comment by ZedThree** [comment]
Is this with the same file as in your first comment?

**Comment by francescotorsello** [comment]
No, the attached reproducer only reproduces the "uppercase bug".

This other error appears when I generate documentation for my real code. For that, the output directory is not a subdirectory of the source directory. I haven't managed to produce a minimal reproducer for it, unfortunately.

**Comment by ZedThree** [comment]
I've got a fix for your first issue, I'll push and make a new release shortly.

It sounds like your other issue is the same as in #303 ?

**Comment by francescotorsello** [comment]
That's great, thank you!

The other issue is indeed the same as in #303 , but it happens to me also when using `sort: type`, not just `sort: type-alpha`.
