### ISSUE TITLE
LaTeX macros

### ISSUE THREAD

**Issue by francescotorsello** [Fortran-FOSS-Programmers/ford#361]
Is it possible to define LaTeX macros?

**Comment by ZedThree** [comment]
It is! I just added some documentation to the wiki about [aliases](https://github.com/Fortran-FOSS-Programmers/ford/wiki/Project-File-Options#alias).

This is simple text-substitution, but you can also define LaTeX macros normally by putting them in `\[...\]` or `$$...$$`:

```latex
$$
   \def\bold#1{{\bf #1}}
$$

$$\bold{x}$$
```

Hope that helps!

**Comment by francescotorsello** [comment]
Thanks, that's great!

Where should I put the definition of the macro, so that Ford does not consider it as documentation to something?

Is it something like this?

```
some code

!!$$
!!  \def\bold#1{{\bf #1}}
!!$$
 
line to be documented using the macro
!! \( \bold(x) \)
```

**Comment by ZedThree** [comment]
The FORD aliases that work like `|this|` should be at the top of the project file, yes. I'm not 100% sure about the LaTeX macros. I have a feeling they would need to be defined basically everywhere you want to use them, which might not be very useful.

We might need to have an option specifically for LaTeX macros to make sure they're defined on every page?

**Comment by francescotorsello** [comment]
Actually, I am trying to define aliases right now, and they do not work...if I write a reproducer I will post it.

About LaTeX macros, I have tried to define them using the code I wrote in the previous comment, but it did not work.

**Comment by ZedThree** [comment]
@francescotorsello #363 should fix your issue with aliases, although there's still an issue that they only work if defined in the project file.

LaTeX aliases work for me, at least as long as they are all in a single FORD docstring.

**Comment by francescotorsello** [comment]
Thanks a lot! 

I think that defining LaTeX macros in each docstring is not the most useful thing; it would be great if one could define them in the project file once, and use them in any source docstring.

However, if aliases now work in the source docstrings, I guess one can just define an alias for the desired LaTeX syntax, and that should do the trick (?)

**Comment by ZedThree** [comment]
Yep, that seems to work.

I'm going to leave this open as a wishlist item for adding something like `latex_def` that is added to each page.

**Comment by francescotorsello** [comment]
Ok great! Is there any plan to release a new version of Ford soonish, with your fix included?

**Comment by ZedThree** [comment]
New version just released with this fix in, should be available via pip in a couple of minutes

**Comment by francescotorsello** [comment]
Thanks!
