### ISSUE TITLE
Typo in latest release version number

### ISSUE THREAD

**Issue by ZedThree** [Fortran-FOSS-Programmers/ford#367]
I made small typo in the tag for the latest release: `v6.15` instead of `v6.1.5`

This is going to cause headaches for the next version number. I think there are three options:

1. Release v6.1.5 on the same commit hash, delete the v6.15 tag, and yank the v6.15 release from PyPI. This leaves it as installable if the exact version is pinned, but otherwise pip will ignore it. This will be a problem if we ever get actually to v6.15.0
2. Same as 1., but delete the v6.15 release. This will break installs for the users who have already pinned v6.15 -- probably not many?
3. The next release is v7.0.0. No problems as far as I can tell, apart from the weird numbering, and that there's currently no backwards-incompatible changes planned so we're not really adhering to semantic versioning.

Option 3 is the least likely to cause problems for users, option 2 will be cleanest in terms of version numbering history, and option 1 somewhere in between.

@cmacmackin Thoughts? Personally, I'm inclined to go for option 2, as we've caught it fairly early and semver is A Good Thing.

**Comment by dschwoerer** [comment]
I think even after deletion 6.15.0 can never be uploaded ... but probably not an issue ...
Anyway yanking it quickly is a good idea, I already have it installed :sweat_smile:

**Comment by ZedThree** [comment]
6.15 has been deleted and 6.1.5 uploaded in its place. For clarity, it's exactly the same files, just the version number has changed

**Comment by ZedThree** [comment]
If you already have 6.15 installed, you will need to `pip install ford==6.1.5` to replace the version. `pip install --upgrade ford` won't work :(
