### ISSUE TITLE
RFE: Links to line number

### ISSUE THREAD

**Issue by dschwoerer** [Fortran-FOSS-Programmers/ford#369]
It would be nice to get links to specific line number(s).

**Comment by ZedThree** [comment]
You mean in docstrings, like `[[filename.f90:84]]`?

**Comment by dschwoerer** [comment]
as in I can append `#ln-40` to reference line 40.
I just checked, and it actually is possible :-D
So a way to make it more easily to discover and use:
```patch
-<a id="ln-61" name="ln-61"></a>
+<a id="ln-61" name="ln-61" href="#ln-61"></a>
```
would be nice :-)

**Comment by ZedThree** [comment]
Understood! That should absolutely be do-able.

**Comment by d7919** [comment]
@ZedThree can this be closed now as complete?
