### ISSUE TITLE
'str object' has no attribute 'meta' - error when abstract interface imported from different module

### ISSUE THREAD

**Issue by SMijin** [Fortran-FOSS-Programmers/ford#372]
Hello, I've encountered the above error when trying to generate documentation for a setup similar to the following:

```
module module1
    
    use module2               ,only: testInterface

    type ,public ,abstract :: testAbstractType

        contains

        procedure(testInterface) ,nopass ,deferred :: testProc

    end type testAbstractType

end module module1

module module2
    
    implicit none
    public

    abstract interface 
    	pure function testInterface(input) result(output)
    	  real ,intent(in) :: input
    	  real                 :: output
    	end function testInterface 
    end interface
end module module2
```

The project file I used to generate the error in the example above:

```
src_dir: ./src/
output_dir: ./doc/
project: test
source: false 
graph: false 
search: false 
display: private
        protected
        public 
```

Moving the abstract interface into the same module resolves the issue, but I'd rather not have to duplicate code. I had a look around closed issues but couldn't find one that matched my case. I'm new to ford, so it could be I'm missing something obvious. 

Thanks,
Stefan

**Comment by ZedThree** [comment]
That definitely looks like a bug to me. Thanks for the report and the reproducer @SMijin !

Unfortunately it might be the new year before I get round to fixing this.
