### ISSUE TITLE
source display broken

### ISSUE THREAD

**Issue by jacobwilliams** [Fortran-FOSS-Programmers/ford#387]
using `source: true` to display the source code seems to have been broken in either `v6.1.7` or `v6.1.8`. 

You can see example [here](https://jacobwilliams.github.io/roots-fortran/proc/brent.html). 

When I revert back to `v6.1.6` it works.

**Comment by ZedThree** [comment]
This was a bit I'd missed when converting all the input settings to `bool`, rather than doing string comparisons everywhere. Fix in #390, plus better tests.

If you're able to try out the various PRs to check they fix your issues, that would be lovely!

**Comment by jacobwilliams** [comment]
thank you! I will test as soon as I can.
