### ISSUE TITLE
Derived Types header missing

### ISSUE THREAD

**Issue by jacobwilliams** [Fortran-FOSS-Programmers/ford#388]
The "Derived Types" header has gone missing sometime after the `6.0.0` release. 

<img width="413" alt="Screen Shot 2022-02-20 at 9 36 28 PM" src="https://user-images.githubusercontent.com/6483379/154885112-de8748b7-bbbf-4c04-ae55-89d9145019e6.png">

**Edit:** Looks like it was broken in `v6.1.3`.

It seems to work if you have:

```yaml
display: public
         private
```

but if you have:

```yaml
display: public
```

Then, even if you do have public derived types, they don't appear.

**Comment by ZedThree** [comment]
Thanks @jacobwilliams ! I've got some better tests on this now.
