### ISSUE TITLE
ford-6.1.8 test: test_projects/test_external_project.py is broken 

### ISSUE THREAD

**Issue by band-a-prend** [Fortran-FOSS-Programmers/ford#395]
While running `test_projects/test_external_project.py` an error arise and test fail:
```
FORD-6.1.8/test/test_projects/test_external_project.py:61: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7ff211ea0be0>

>   links = {tag.text: tag.a["href"] for tag in uses_box("li", class_=None)}
E   TypeError: 'NoneType' object is not subscriptable

.0         = <list_iterator object at 0x7ff211ea0be0>
tag        = <li>aot_out_module</li>

FORD-6.1.8/test/test_projects/test_external_project.py:61: TypeError
```

P.S.
Reproduced for python versions 3.8, 3.9, 3.10 while preparing gentoo::guru package.
Ford-6.1.7 is not affected as appropriate changes were made in https://github.com/Fortran-FOSS-Programmers/ford/commit/1d08640de01f1c5ba23c38ea4ff6cce6a8a59e50

**Comment by ZedThree** [comment]
Ah, I was worried that could fail. It's testing getting an external project via https, and I guess the test server can't access that address. Maybe the test would work better if instead we mocked `urlopen`, that way we wouldn't rely on an external resource.
