### ISSUE TITLE
FORD tries to run the preprocessor even if preprocessor test failed

### ISSUE THREAD

**Issue by mbraakhekke** [Fortran-FOSS-Programmers/ford#398]
If option `preprocess` is set to `true` (the default) FORD (in `__init__::parse_arguments()`) tests the preprocessor command set in option `preprocessor`. If the test fails, the following warning is displayed:

```
Warning: Testing preprocessor failed
  Preprocessor command: ['cpp', '-traditional-cpp', '-E', '-D__GFORTRAN__']
  Exception: [WinError 2] The system cannot find the file specified
  -> Preprocessing turned off
```

However, at a later stage the preprocessor is run anyway and FORD errors out.

`__init__::parse_arguments()` sets the option `preprocess` to `False` if the test fails but it seems that this option is not used elsewhere to check if the files should be preprocessed.
Easiest solution would be to error out directly if the test fails. This seems reasonable to me. But then I guess the default for `preprocess` should change to `false`.

**Comment by ZedThree** [comment]
Oops, we should set `preprocessor = None` instead (or as well).

It would be nicer perhaps to hard error if the user explicitly requests preprocessing but we can't, but off the top of my head I'm not sure how to do that. `preprocess = auto/True/False` might be one way, where by default we try, and if it works then we enable it, but if set to `True` explicitly then we error. I'll have to think about how that would actually work though

**Comment by mbraakhekke** [comment]
I'm not sure I follow. The test is only run if `preprocess==True` so why not simply raise an error if the test fails?

**Comment by ZedThree** [comment]
I mean, that is certainly an option, I'm just a little wary because `preprocess == True` is the default value. If a user doesn't care about preprocessing, and the check fails, then they would have to modify the config file, while currently it would run fine (but print a warning). That's not the end of the world but it is a change in behaviour.

If we did change the behaviour to hard error instead of a warning, we could make the error message nicer and explain how to disable or fix the check

**Comment by ZedThree** [comment]
I thought about it some more, and I think immediately aborting with a helpful error message is the more sensible option, so I've done that in #393 which I fixed another related bug

**Comment by mbraakhekke** [comment]
👍 thanks!
I assume it's not really necessary that I test it, right?
