### ISSUE TITLE
Add the possibility to use inline comments

### ISSUE THREAD

**Issue by fedebenelli** [Fortran-FOSS-Programmers/ford#402]
Having to document each variable before (or after) it's definition makes the subroutines/functions headers unnecessary long in my opinion. Even more if the definitions are really simple.

Could the possibility of describing the variables inline be added? At least I couldn't find it in the documentation.

Simple example:

```fortran
      !> Critical temperature
      real(8), intent(in) :: Tc 
      !> Critical pressure
      real(8), intent(in) :: Pc 
      !> Accentric factor
      real(8), intent(in) :: w 
      !> Gas constant
      real(8), intent(in) :: R 

      !> ac parameter
      real(8), intent(out) :: ac 
      !> Covolume
      real(8), intent(out) :: b 
      !> Constant to calculate a(T)
      real(8), intent(out) :: m 
```

vs

```fortran
      real(8), intent(in) :: Tc !< Critical temperature
      real(8), intent(in) :: Pc !< Critical pressure
      real(8), intent(in) :: w !< Accentric factor
      real(8), intent(in) :: R !< Gas constant

      real(8), intent(out) :: ac !< ac parameter
      real(8), intent(out) :: b !< Covolume
      real(8), intent(out) :: m !< Constant to calculate a(T)
```

**Comment by ZedThree** [comment]
FORD support both pre- and post-docmarks out of the box, and post-docmarks work inline. The default post-docmark is `!` (so the comments are `!!`), so the following works out of the box and does what you want:

```fortran
      real(8), intent(in) :: Tc !! Critical temperature
      real(8), intent(in) :: Pc !! Critical pressure
      real(8), intent(in) :: w !! Accentric factor
      real(8), intent(in) :: R !! Gas constant

      real(8), intent(out) :: ac !! ac parameter
      real(8), intent(out) :: b !! Covolume
      real(8), intent(out) :: m !! Constant to calculate a(T)
```

If you would like to use `!<` for inline comments, you can set the following in your config file: `docmark: <`

You're right, this isn't mentioned in the documentation -- we could really do with tidying them up I think

**Comment by fedebenelli** [comment]
Thanks for the clarification! I'll see if I can make a pull request with that detail
