### ISSUE TITLE
Include project readme.md

### ISSUE THREAD

**Issue by Koushikphy** [Fortran-FOSS-Programmers/ford#403]
Is there a way to include the Readme.md file of a project directly to the homepage of the ford documentation? My project has a readme.md file that has all the necessary information for compilation, installation and usage and I don't want to write the same thing in the markdown file for `ford`. Is there a way to include the already written content of the readme file during the ford usage?

**Comment by ZedThree** [comment]
Yep, you can use `{!README.md!}` to include the file. There is a bit about it in the [wiki](https://github.com/Fortran-FOSS-Programmers/ford/wiki/Writing-Documentation#include-capabilities), but it is hidden away a little.

**Comment by Koushikphy** [comment]
Ok, that solves my problem.
