### ISSUE TITLE
Markdown checkboxes are not properly rendered in pages

### ISSUE THREAD

**Issue by Koushikphy** [Fortran-FOSS-Programmers/ford#406]
I have an checklist in one my my pages, like this 

- [ ] item1
- [ ] item2
- [ ] item3

But after its compiled to HTML by `ford`, the checklist is not rendered in the HTML page, it shows something like this

- [] item1
- [] item2
- [] item3

Is it a bug or I have to do something different to render the checklist properly.

**Comment by ZedThree** [comment]
Checklists aren't part of the markdown dialect we use\*, but there is at least one extension that enables them: https://github.com/FND/markdown-checklist

To use this extension, you first need to install it on the system where you're running Ford, and add the following to the top of your Ford config file:

```markdown
md_extensions: markdown_checklist.extension
```

That should be sufficient to render the checklists

---


\* There are, unfortunately, many different dialects/flavours of markdown. We use python-markdown but, for example, GitHub uses a different dialect called "GitHub Flavoured Markdown" that _does_ render checkboxes
