### ISSUE TITLE
Hide listing from bottom of front page

### ISSUE THREAD

**Issue by Gfacco** [Fortran-FOSS-Programmers/ford#409]
Is there a way to hide the partial listing at the bottom of the landing page generated by FORD?

**Comment by ZedThree** [comment]
You could try setting `max_frontpage_items` to 0

On the wishlist is adding a better, more customisable template/theme system for the pages which would give users more control over how they look, but that is probably a long way I'm afraid

**Comment by Gfacco** [comment]
this works to eliminate the lists, but the column headers are still shown

**Comment by ZedThree** [comment]
Fixed in #496
