### ISSUE TITLE
tying documentation to a generic name

### ISSUE THREAD

**Issue by urbanjost** [Fortran-FOSS-Programmers/ford#412]
I cannot seem to find any method of tying documentation to a generic routine in a module. If I place the commands before the CONTAINS it shows up as documentation for the module, if I place it in one of the routines it shows up for that routine but not the others.
I was looking for a location where the documentation would show up for the generic name and maybe all the routines associated to the generic. 

If is fine if just defining one generic in a module, but when defining multiple procedures in the same module it is less than ideal. 
Did I miss something?  If not, something where !>>NAME   would associate the following comments to that routine no matter where it occurs in the file would be nice.

**Comment by ZedThree** [comment]
This should work already:

```fortran
module test_module
  implicit none

  interface increment
    !! Generic increment
    module procedure increment_int, increment_real
  end interface increment

contains
  subroutine increment_int(x)
    !! Increase argument by one
    integer, intent(inout) :: x
    x = x + 1
  end subroutine increment_int

  subroutine increment_real(x)
    !! Increase argument by one
    real, intent(inout) :: x
    x = x + 1
  end subroutine increment_real
end module test_module
```

results in:

![image](https://user-images.githubusercontent.com/1486942/165275507-bb0424c4-5a04-463b-9f9c-f5deb4f1432e.png)

Could you post an example that isn't working for you?

**Comment by urbanjost** [comment]
It does appear to be working locally,  this must be an issue with my CD/CI builds (everything goes through a preprocessor) so I will close this. The help text was originally written for txt2man(1) so this is a work in progress, but so far looks like this:

 https://urbanjost.github.io/orderpack/fpm-ford/index.html
