### ISSUE TITLE
Links to static pages

### ISSUE THREAD

**Issue by Meax5qiu** [Fortran-FOSS-Programmers/ford#414]
How to link to static pages? I have several plain Markdown files in the directory referenced by the `-p` CLI option of `ford`. In there (and in the comments within source files), I can happily link to other source files, but I have not found a documented way to link to static pages, nor discovered one by trying out.

Have I overlooked something, or are static pages intended to only talk to each other by the table of contents?

**Comment by Meax5qiu** [comment]
Any news on this? I don't want to teach to my end users the horrible anti-pattern to put absolute file paths into links.
Oh well, if there really is no way to get Wiki-style internal links between static pages running, we'll have to resort to adding `.html` boilerplate to many many links.

**Comment by ZedThree** [comment]
Hi @Meax5qiu , sorry for the slow reply, it's been a very busy month!

Currently, the only way is use the full path, although we have a [`|url|`](https://github.com/Fortran-FOSS-Programmers/ford/wiki/Writing-Documentation#macros) macro that expands to the project URL. So you can link to `|url|/page_dir/directory/index.html`.

Being able to link to static pages through some short form would be a really useful feature though.

**Comment by haraldkl** [comment]
Actually the wiki entry for aliases seems to be lacking one predefined macro. There is [one for pages](https://github.com/Fortran-FOSS-Programmers/ford/blob/52258480d517083c26fb9d17662457907f754214/ford/__init__.py#L573). Thus, you can use `|page|`, still needs the HTML filename, though.

**Comment by haraldkl** [comment]
I've updated the wiki on [Writing Pages](https://github.com/Fortran-FOSS-Programmers/ford/wiki/Writing-Pages) to include a hint for the `|page|` macro now.

**Comment by ZedThree** [comment]
Fantastic, thanks @haraldkl !
