### ISSUE TITLE
Update bootstrap CSS

### ISSUE THREAD

**Issue by awvwgk** [Fortran-FOSS-Programmers/ford#445]
The currently generated output is based on bootstrap 3

https://github.com/Fortran-FOSS-Programmers/ford/blob/29063388bcee4e1b650071e1025a8fb16ee724f2/ford/css/bootstrap.css#L2

Updating to bootstrap 4 or 5 would give all generated docs access to somewhat more modern look of the newer bootstrap versions.

**Comment by ZedThree** [comment]
Good idea! Do you know if the more recent versions are backwards compatible? Some people might have custom site CSS, and I would be a little wary of breaking that -- or rather, I don't mind breaking that, but only in a new major/minor version (depending on level of breaking-ness).

Going one step further, perhaps switching to https://semantic-ui.com might be even better. It has a variety of themes builtin, including bootstrap.
