### ISSUE TITLE
Broken link in derived type constructors

### ISSUE THREAD

**Issue by HugoMVale** [Fortran-FOSS-Programmers/ford#456]
A while ago, I mentioned a similar issue #450, with type-bound procedures. That was solved. However, a similar problem can still be observed for user-defined constructors, as illustrated [here](https://hugomvale.github.io/HR-WENO/type/weno.html) . Clicking "Read more..." will return 404.

**Comment by ZedThree** [comment]
@HugoMVale Can you check #457 ? I've now also added a test that checks all internal links in the documentation do resolve to generated pages (and existing anchors). Unfortunately, it's really quite a lot of effort to check every single situation, so bug reports like this are really useful to add new cases to the test suite!
