### ISSUE TITLE
absolute paths to src_dir

### ISSUE THREAD

**Issue by mcocdawc** [Fortran-FOSS-Programmers/ford#458]
Hello,

We use `ford` to build the documentation for our project and would like to support out-of-source builds.
With new versions of ford this is not possible anymore, since the existence of a `./src` subdirectory is implicitly assumed.
Even when passing other absolute paths, it still checks the existence of a `./src` subdirectory, which fails if we have a separate ford work directory in our build directory.

Some of the relevant lines are:
```python3
# https://github.com/Fortran-FOSS-Programmers/ford/blob/master/ford/__init__.py#L197
"src_dir": ["./src"],

# https://github.com/Fortran-FOSS-Programmers/ford/blob/master/ford/__init__.py#L251
    parser.add_argument(
        "-d",
        "--src_dir",
        action="append",
        default=["./src"],
        help="directories containing all source files for the project",
    )
```

Do you plan to again support pure absolute paths?

**Comment by ZedThree** [comment]
Ah, that's a bug, sorry! If you can, please could you throw together a very simple test case, as that would help me fix it faster!
