### ISSUE TITLE
Macros/aliases path-depth dependent on static pages, when project_url is not defined

### ISSUE THREAD

**Issue by Meax5qiu** [Fortran-FOSS-Programmers/ford#461]
Our `index.md` does not define `project_url`, and this is something we want to keep if possible (e. g. to still be able to test the HTML pages locally before deployment). Per its documentation:

>The URL at which the documentation will be available. If left blank then relative URLs will be used for links.

For what _relative_ means here, I had wrongly assumed that `|url|` (and consecutively other macros like `|media|`) would use URLs relative _to the project_. But rather, they are relative _to the current page_.

That means, that, say to include an image from the media directory into a static page, I have to prepend the `|media|` path with as many '../''s as its directory tree depth. Less than optimal when files are moved around.

(This is different from #414, where we are making use of `[link text](../|page|/path/somepage.html)` hack, to link to the static page made from `path/somepage.md` – but there we have the advantage of the flat source file structure, i. e. one `../` is always sufficient.)

**What to do about this?** I think that a Ford user should not need to know such details about the final HTML file structure. The `|page|`, `|media|` etc. shortcuts should do the same thing from a logical perspective, i. e. be reliable aliases to the paths relative to the project root: regardless if it's inline comments in the sources, or static pages, regardless at which directory depth the files are placed, regardless if `project_url` is set or not.

I imagine that keeping track of the current directory depth when processing a static or source file (to count `../`) is probably not hard. Unlike the extension of the semantics of macros/aliases, that would be necessary (distinction between simple and path-like macros).

**Comment by ZedThree** [comment]
Fixed in #562
