### ISSUE TITLE
ford-6.1.17 fail tests with python3.11

### ISSUE THREAD

**Issue by band-a-prend** [Fortran-FOSS-Programmers/ford#466]
I tried to package ford-6.1.17 with python3.11 support and get tests fail:

short test summary info
```
ERROR test/test_sourceform.py - ValueError: mutable default <class 'test_sourceform.FakeParent'> for field parent is not allowed: use default_factory
```

The full test log is attached ([ford-6.1.17_fail_test_python3.11.log](https://github.com/Fortran-FOSS-Programmers/ford/files/10474912/ford-6.1.17_fail_test_python3.11.log))

**Comment by ZedThree** [comment]
Thanks for the bug report @band-a-prend ! This is fixed in master now

**Comment by band-a-prend** [comment]
Great thanks for fix!
