### ISSUE TITLE
Links to SUBMODULES

### ISSUE THREAD

**Issue by francescotorsello** [Fortran-FOSS-Programmers/ford#499]
Hello,

Does FORD support links to SUBMODULES?

Referencing a `SUBMODULE (mod) subm` of `MODULE mod` with `[[subm]]` , `[[mod:subm]]` or `[[mod@subm]]` does not work.

**Comment by ZedThree** [comment]
This is indeed missing I'm afraid. I think #410 looked at implementing links differently, which would be really nice to finish off and get in at some point.

For the time being, I think it might be as simple as expanding the dict of link types: https://github.com/Fortran-FOSS-Programmers/ford/blob/21d98e5349c048d53eda7a228147ada57755b855/ford/utils.py#L189-L190

to include `"submodule": "submodules",`. PRs welcome! :smile:
