### ISSUE TITLE
Support name attribute for BIND

### ISSUE THREAD

**Issue by RRiva** [Fortran-FOSS-Programmers/ford#506]
Specifying the name with which a subroutine is exported, like for example
```
subroutine init() bind(C, name='init')
end subroutine init
```

Produces in the html
```
public subroutine init() bind(C, name="0")
```
It would be nice to support the `name` attribute of `bind`.

**Comment by ZedThree** [comment]
This is almost certainly a bug -- strings get replaced by tokens during parsing, and should be subbed back in afterwards.
