### ISSUE TITLE
Abstract method info displayed instead of concrete method info

### ISSUE THREAD

**Issue by patflynngithub** [Fortran-FOSS-Programmers/ford#507]
I had a problem where a method's abstract definition is being displayed in FORD-generated doc instead of the concrete version of the method. I found a "fix" to this (commented Fortran code). I have toy code below that demonstrates this. You can decide if you want to support the pre-"fix" code.

```
!> mod_external_abstract module
module mod_external_abstract

implicit none

!> type definition in external_class_t class
type, abstract :: abstract_external_class_t

private

contains

   !> procedure declaration inside abstract_external_class_t class
   procedure(output_int_ext), deferred :: output_int_ext

end type abstract_external_class_t

abstract interface

!> subroutine output_int_ext method of abstract interface in mod_external_abstract module
subroutine output_int_ext(this, an_int)
   import abstract_external_class_t
   implicit none
   class(abstract_external_class_t), intent(in) :: this
   integer, intent(in)                 :: an_int     !! dummy variable declaration in abstract_interface output_int_ext in mod_external_abstract
end subroutine output_int_ext

end interface

end module mod_external_abstract
```
```
!> mod_external module
module mod_external

use mod_external_abstract, only : abstract_external_class_t

implicit none

private

public :: external_class_t

!> type definition in external_class_t class
type, extends(abstract_external_class_t) :: external_class_t

   private

contains

   !> procedure declaration inside external_class_t class
   procedure output_int_ext
   ! procedure :: output_int_ext
    
end type external_class_t

contains

!> subroutine output_int method of external_class_t in mod_external module
subroutine output_int_ext(this, an_int)

   implicit none

   class(external_class_t), intent(in) :: this
   integer, intent(in)                 :: an_int     !! dummy variable declaration mod_external

   write (*,*) "an_int = ", an_int

end subroutine output_int_ext

end module mod_external
```
### Problem
- mod_external module webpage: external_class_t entry
  - output_int_ext method is listed as a component (w/ external_class_t autodoc comment)
  - output_int_ext method is also listed as a type-bound procedure (as should be), but is and links to the abstract_external_class_t version
- external_class_t webpage
  - output_int_ext method listed is the abstract_external_class_t version

### Fix
- the "procedure output_int_ext" statement in the contains section of the external_class_t derived type definition
  - the "procedure output_int_ext" syntax works in Intel and gfortran compilers
  - reading (e.g. Modern Fortran explained) shows that there should "officially" be two colons added
      - procedure :: output_int_ext
      - doing this makes the proper output_int_ext external_class_t version be displayed on the mod_external and external_class_t webpages

**Comment by ZedThree** [comment]
This is fixed in #512 and will be in v6.2.5 shortly
