### ISSUE TITLE
[Bug] Encoding in the project file (`FORD.md`) does not take effect in the page file (`index.md`, etc)

### ISSUE THREAD

**Issue by zoziha** [Fortran-FOSS-Programmers/ford#518]
This happened to me using Ford on **zh-cn_Windows_10** OS:
My Fortran source code and `doc/index.md` are both in **Chinese and UTF-8 format**. When building with FORD, I get an error:
```sh
> ford FORD.md
...
Reading page .. \doc\index.md
Warning: Error parsing .. \doc\index.md.
        gbk
...

> cat ./doc/index.md
---
title: Specification
---

@warning
本文档是一个简易的规范文档，仅供参考。
```

Because zh-cn_Windows_10 OS uses **GBK encoding by default**, but because `encoding` of the FORD project file (`FORD.md`) does not take effect on `doc/index.md`, there is an error. I believe it is related to the following line of code:
https://github.com/Fortran-FOSS-Programmers/ford/blob/62b8d7fd2f04388b466533671e7c6e193128b71b/ford/pagetree.py#L37-L38

If `encoding=` can be explicitly declared in `open` function, or this problem can be resolved?

Thanks in advance！

**Comment by ZedThree** [comment]
This definitely is definitely a bug, thanks @zoziha! We have a setting [`encoding`](https://forddocs.readthedocs.io/en/latest/user_guide/project_file_options.html#encoding) which is supposed to be applied to all files, and defaults to UTF-8.

Actually, it seems we explicitly open the project file (`FORD.md` in your case) as UTF-8 -- we maybe need a command line option to change this.

We should pass the `encoding` down to here. I'll see if I can get this fixed this week, but it might be the end of the week before I get chance. Happy to accept PRs, especially if you are able to add a test case!
