### ISSUE TITLE
Resolving links in submodules

### ISSUE THREAD

**Issue by runburg** [Fortran-FOSS-Programmers/ford#523]
I am having trouble using links from within submodules. Things like `[[my_component(my_type)]]` appear to not be parsed at all when they are in documentation within submodules and just appear verbatim in the resulting html.

Does this feature exist?

Thanks!

**Comment by ZedThree** [comment]
This should work, I'll look into it

**Comment by ZedThree** [comment]
@runburg I wasn't able to quickly reproduce this -- please could you post a minimal example?
