### ISSUE TITLE
Using external option from GitHub Actions script

### ISSUE THREAD

**Issue by patflynngithub** [Fortran-FOSS-Programmers/ford#549]
I am working with the FORD external/externalize option to link separate FORD projects. It works fine when everything is present and done locally on my PC (source code and FORD doc storage)

`external: mod_external = ../../mod_external/docs/ford_fortran_doc_api_only/`

However, it doesn't work properly when I try to do the same from an Actions script on our internal GitHub server. The externalized FORD project has already been generated and is stored on an internal GitHub Pages website (within our *docs/* repo that hosts all the online doc for this project's GitHub organization). The main FORD project (is in same organization) using the external option is being saved to the same GitHub pages website.

`external: mod_external = https://github.company_name.com/pages/org_name/docs/mod_external/ford_fortran_doc_api_only/`

When the

`ford project.md'

command is run on the project with the external option, FORD generates the following non-fatal error:

```
Processing documentation comments...
Correlating information from different parts of your project...
Could not open external URL '//github.company_name.com/pages/org_name/docs/mod_external/ford_fortran_doc_api_only/', reason: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
```

Same error happens when using `http`

The FORD doc is generated, but any `mod_external` "links" are just displayed text w/o any underlying links.

**Comment by ZedThree** [comment]
It sounds like the Actions runner doesn't have the SSL certificates set up correctly. If it works locally using the full correct URL, then it's certainly the runner. You'll have to look at how to tell the Action where the SSL certificates are.
