### ISSUE TITLE
Nested link for intrinsic `iso_fortran_env` module

### ISSUE THREAD

**Issue by interkosmos** [Fortran-FOSS-Programmers/ford#564]
If a Fortran module or procedure imports the `iso_fortran_env` module, the `href` attribute of the `<a>` link placed under _Uses_ (above the dependency graph) includes another `<a>` tag:

```html
<li class="list-group-item">
    <ul class="list-inline">
        <li><a href="<a href=&quot;http://fortranwiki.org/fortran/show/iso_fortran_env&quot;>iso_fortran_env</a>">iso_fortran_env</a></li>
        <li><a href="https://www.example.com/doc/module/my_mod.html">my_mod</a></li>
    </ul>
</li>
```

**Comment by ZedThree** [comment]
Thanks for the bug report @interkosmos, is this with the latest `master` branch or a released version?
