### ISSUE TITLE
Test failures on Fedora linux

### ISSUE THREAD

**Issue by bkmgit** [Fortran-FOSS-Programmers/ford#567]
When building on Fedora linux Rawhide (40), the test suites that pass are:
- test_graphs.py
- test_md_environ.py
- test_md_table.py
- test_pagetree.py
- test_reader.py
- test_sourceform.py
- test_reader.py
Others fail.  Can add a containerized Fedora build and test to CI if it would be of interest. 

Would also be great to relax dependency version requirements in pyproject.toml to:
```
markdown-include >= 0.7.0
python-markdown-math >= 0.8
toposort >= 1.7.0
pygments >= 2.12.0
graphviz >= 0.20.0
tqdm >= 4.64.0
```

**Comment by ZedThree** [comment]
Oh dear, do they all fail with similar errors? There have been quite a few changes since the last release, so it would be interesting to know if they still fail on current `master`.

Happy to relax those dependency requirements, though I'll need to double-check none of them have breaking changes.
