### ISSUE TITLE
Three potential issues with version 7.0

### ISSUE THREAD

**Issue by zoziha** [Fortran-FOSS-Programmers/ford#575]
It's good to see that FORD has released version 7.0, I did my first try and found three issues:
1. **Page Code blocks do not have a background color**, making it difficult to distinguish between the code block and the body.
![image](https://github.com/Fortran-FOSS-Programmers/ford/assets/32035096/e4767505-dc1a-4f83-a09f-3d18fcda6aac)

3. When the Page code block is **too wide**, the style changes: the overall style appears to be shifted down.
![image](https://github.com/Fortran-FOSS-Programmers/ford/assets/32035096/55edf5ce-5cc1-4617-b205-3c7af3ef4237)
Ford-0.6 style:
![image](https://github.com/Fortran-FOSS-Programmers/ford/assets/32035096/e220f528-f211-4813-b875-82d7345135cd)

5. **Count the source file** 1 time repeatedly.
![image](https://github.com/Fortran-FOSS-Programmers/ford/assets/32035096/70b50c73-57a9-4241-b766-582643d324d2)

Examples of specific projects can be found at repo: [ford-bugs](https://github.com/zoziha/ford-bugs).

**Comment by ZedThree** [comment]
I can't reproduce the repeated source file. Please could you check that you don't have something like a temporary file that's getting picked up?

**Comment by zoziha** [comment]
@ZedThree Maybe it has something to do with the fact that I'm using Windows OS, I'm getting 2x source file counts with Ford-v7.0 on both Windows computers, and [there are people in Fortran Discourse who have had similar experiences](https://fortran-lang.discourse.group/t/ford-fortran-documentation-generator-new-major-release-v7-0-0/6647/2?u=zoziha).
The [ford-bugs](https://github.com/zoziha/ford-bugs) repository is all the files, there should be no extra temp files?

**Comment by ZedThree** [comment]
Ah, I think this is because Windows filesystems are (by default) case insensitive, so when we get a list of files, the upper/lower case extensions (with/without preprocessor for gfortran on Linux) match the same files. I think it should be sufficient to change a `list` to a `set`
