### ISSUE TITLE
Use a maintained javascript search engine

### ISSUE THREAD

**Issue by bkmgit** [Fortran-FOSS-Programmers/ford#587]
[tipuesearch](https://github.com/Fortran-FOSS-Programmers/ford/blob/master/ford/tipuesearch/tipuesearch.js) is no
longer actively maintained. Could it be replaced by one of:

- [lunr](https://github.com/olivernn/lunr.js)
- [minisearch](https://github.com/lucaong/minisearch)
-

**Comment by ZedThree** [comment]
minisearch looks like it's more regularly maintained. PRs welcome! :)
