### ISSUE TITLE
Dependency graphs not displayed correctly

### ISSUE THREAD

**Issue by jacobwilliams** [Fortran-FOSS-Programmers/ford#610]
I've noticed the dependency graphs don't seem to be displayed correctly like they were before. They are too big and are getting cropped or something. Example:

<img width="1203" alt="Screenshot 2024-01-04 at 5 24 19 PM" src="https://github.com/Fortran-FOSS-Programmers/ford/assets/6483379/bff04d6c-0927-4d26-a9e5-1435cd229064">

**Comment by ZedThree** [comment]
This was fixed in #599 and is now available in v7.0.4 (just released)

**Comment by kc9jud** [comment]
This appears to be a problem again with v7.0.6.
