### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jacobwilliams** [Fortran-FOSS-Programmers/ford#611]
Something is broken with links like this:

```fortran
!### See also
!  * [fmin from Netlib](http://www.netlib.org/fmm/fmin.f)
```

Result is:

<img width="330" alt="Screenshot 2024-01-06 at 9 36 12 AM" src="https://github.com/Fortran-FOSS-Programmers/ford/assets/6483379/9d519908-fbdc-47bf-a5f6-fd6c620b97ad">

See here: https://jacobwilliams.github.io/fmin/proc/fmin.html

**Comment by ZedThree** [comment]
Thanks for the bug report @jacobwilliams, turns out this was from switching to the `pcpp` preprocessor which was parsing `http://` as ending in a (C/C++) comment and clobbering the rest of the line.
