### ISSUE TITLE
Problem with the link in the header menu

### ISSUE THREAD

**Issue by gha3mi** [Fortran-FOSS-Programmers/ford#613]
When clicking on the Program link, it correctly directs to the intended page. However, upon clicking on the Program link again on the Program page, it leads to an invalid page. It attempts to open `program/program/<mypage>.html` instead of `program/<mypage>.html`.

Thanks
Ali

**Comment by gha3mi** [comment]
The same issue occurs on other pages for the program link.

**Comment by ZedThree** [comment]
Thanks for the bug report @gha3mi, this is now fixed
