### ISSUE TITLE
Navigation Bar Issue: Incorrect Link Path for 'Program' on Derived Types Pages

### ISSUE THREAD

**Issue by gha3mi** [Fortran-FOSS-Programmers/ford#615]
Thank you for the quick bug fixes related to #613.

There is a similar issue on the _Derived Types_ pages concerning the _Program_ link on the navigation bar. It attempts to open `lists/program/<my_program>.html` instead of `/program/<my_program>.html`.

Thanks
Ali

**Comment by ZedThree** [comment]
Hi @gha3mi, sorry I've not been able to reproduce this. As all the pages inherit the `base.html` template, I'm also a bit stumped how this would only happen on a single page. Please could you double-check you're using the latest version and have refreshed your browser cache?

**Comment by mscfd** [comment]
Accidentially I think I have just hit the same error but for sourcefile link in the navigation bar.
For the very simple project source:

```
module test

implicit none
public

contains

subroutine sub1()
end subroutine sub1

end module test
```

Starting from the main index.html, the link to "Source File" works fine. But if I first hit "Modules" and then "Source File" in the navbar, the page is not found. The difference is that in the first case `.../sourcefile/test.f90.html` is loaded, in the second case `lists/sourcefile/test.f90.html`. Just as described above for program.

**Comment by gha3mi** [comment]
> Hi @gha3mi, sorry I've not been able to reproduce this. As all the pages inherit the `base.html` template, I'm also a bit stumped how this would only happen on a single page. Please could you double-check you're using the latest version and have refreshed your browser cache?

Thank you for your response. I deploy documentation on GitHub using FORD within CI, and it appears that the problem has now disappeared. I'm not sure exactly why this happened, but as you mentioned, it could have been related to the browser cache or ....

**Comment by ZedThree** [comment]
Thanks @mscfd, I tracked this down and one other similar bug
