### ISSUE TITLE
Can't link from a page to source code

### ISSUE THREAD

**Issue by fedebenelli** [Fortran-FOSS-Programmers/ford#626]
I'm trying to link from a page to the documentation of a module of my code but I doesn't seem work right. I've followed the https://github.com/Fortran-FOSS-Programmers/ford/wiki/Writing-Documentation#links instructions but the generated links points to a substructure in the page folder.

As an example, if I want to link to module `my_mod` from a page I write "you can see more info about `my_mod` at [[my_mod(module)]]". And the link points to `ford_site_dir/page_dir/module/my_mod.html` instead of `ford_site_dir/module/my_mod.html`. I don't know if this is a bug or I'm doing something wrong. 

Thank you for your work! I'm very grateful of having nice documentation on Fortran :)

**Comment by ZedThree** [comment]
@fedebenelli That certainly sounds like a bug. Please could you tell me what version of Ford you're using? The latest version is 7.0.5, for reference.

Please could you also provide a minimal example? That will help me track the bug down much faster

**Comment by ZedThree** [comment]
Great, glad it's fixed!
