### ISSUE TITLE
Online documentation outdated?

### ISSUE THREAD

**Issue by coriollis-nico** [Fortran-FOSS-Programmers/ford#655]
Hello, new user here.

I was unsure if the online documentation is slightly out of date? `latest` (the default) shows `6.2.6.dev.278+g6895713` while `stable` shows `6.2.5`.
I haven't stumbled upon anything that doesn't work anymore, but I was wondering if the online docs can still be considered suitable for the current version.

And btw thank you for developing Ford! Fortran feels so much more fresh when tools like these are developed for it.

**Comment by ZedThree** [comment]
Thanks for pointing this out! Turns out the doc builds have been failing for quite a while :facepalm: I usually set up doc build tests on PRs, but it looks I've not done that for this project.
